apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: frontend-app
  name: frontend-app
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: frontend-app
  type: NodePort
status:
  loadBalancer: {}
