apiVersion: batch/v1
kind: CronJob
metadata:
  name: ping-cronjob
  namespace: exam-dilshod-xolmatov  
spec:
  schedule: "*/2 * * * *"  
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: ping
            image: busybox  
            command: ["/bin/sh", "-c"]
            args:
              - while true; do ping -c 4 8.8.8.8; sleep 120; done
          restartPolicy: OnFailure
