apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: repo-2
  name: repo-2-svc
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: repo-2
status:
  loadBalancer: {}
