apiVersion: v1
kind: LimitRange
metadata:
  name: resource-limits
  namespace: exam-dilshod-xolmatov  # Replace with your namespace
spec:
  limits:
  - type: Container
    max:
      cpu: "1"
    min:
      cpu: "50m"
    default:
      cpu: "200m"
    defaultRequest:
      cpu: "100m"
  - type: Pod
    max:
      cpu: "1"
    min:
      cpu: "50m"
