apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2024-08-14T16:04:24Z"
  generation: 1
  labels:
    app: repo-2
  name: repo-2
  namespace: exam-dilshod-xolmatov
  resourceVersion: "7030746"
  uid: 335021d7-893e-4d22-894f-09aba7e830c1
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: repo-2kubectl scale deployment repo-2 --replicas=3

  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: repo-2
    spec:
      containers:
      - env:
        - name: ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              key: env
              name: info
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              key: log_leveI
              name: info
        - name: GRPC_PORT
          valueFrom:
            configMapKeyRef:
              key: grpc_port
              name: info
        - name: POD_ID
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        image: dilsh0dev/js:v1
        imagePullPolicy: IfNotPresent
        name: repo-2
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2024-08-14T16:04:26Z"
    lastUpdateTime: "2024-08-14T16:04:26Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2024-08-14T16:04:24Z"
    lastUpdateTime: "2024-08-14T16:04:26Z"
    message: ReplicaSet "repo-2-7fd45f4949" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
